### ISSUE TITLE
Build on ios 10.12.5

### ISSUE THREAD

**Issue by YuriZheng** [manasthakur/tech#1]
I want to build openjdk 8 on my mac, the system is sierra 10.12.5, I got the openjdk's source code, and then is run "bash ./configure", but it's wrong --- "Xcode 4 is required to build JDK 8, the version found was 8.3.3. Use --with-xcode-path to specify the location of Xcode 4 or make Xcode 4 active by using xcode-select."

I download xcode 4 and move it to /Applications/Xode4/Xcode.app, run whit "bash configure --with-xcode-path=/Applications/Xcode4/Xcode4.app", but it show that xcode4 can't support on this system.

I don't know how to do, please help me!

**Comment by YuriZheng** [comment]
@manasthakur

**Comment by manasthakur** [comment]
Hi @YuriZheng,

Sorry for the (very) late reply.
Unfortunately, I think it's not possible any longer to make Xcode4 work on the newer versions of macOS. The only option to develop OpenJDK8 seems to be a Linux OS now.

**Comment by YuriZheng** [comment]
So you mean than it's not work on mac to build openjdk8?
Your suggestion is to install a Linux system virtual machine to build it?

**Comment by manasthakur** [comment]
Yes. Or the other solution is to degrade your OS to Yosemite. The first solution obviously seems better.

**Comment by YuriZheng** [comment]
Thank you all the same, I try it on virtual machine!
